"""
Post Analysis Synthesizer Agent

This agent analyzes and synthesizes content generated by
multiple social media platform agents.

The agent evaluates:
- Engagement quality
- Platform optimization
- CTA effectiveness
- Readability
- Virality potential
- Brand consistency
- Audience targeting
- Marketing effectiveness
"""

import os

from google.adk.models.lite_llm import LiteLlm
from google.adk.agents import LlmAgent


# -----------------------------
# Model Configuration
# -----------------------------

GEMINI_MODEL = "gemini-2.5-flash-lite"

model = LiteLlm(
    model="groq/openai/gpt-oss-120b",
    api_key=os.getenv("GROQ_API_KEY"),
)


# -----------------------------
# Post Analysis Agent
# -----------------------------

post_analysis_agent = LlmAgent(
    name="PostAnalysisSynthesizer",

    model=GEMINI_MODEL,

    description="""
    Analyzes and synthesizes social media content
    generated across multiple platforms.
    """,

    instruction="""
    You are an advanced Social Media Content Analysis Agent.

    Your responsibility is to analyze and compare
    social media content generated for:

    - Facebook
    - Instagram
    - WhatsApp

    You will receive:
    - Facebook post: {facebook_post}
    - Instagram caption: {instagram_caption}
    - WhatsApp message: {whatsapp_message}

    Your analysis must include:

    1. Executive Summary
       - Overall campaign quality
       - Brand consistency
       - Cross-platform effectiveness

    2. Platform-Specific Analysis
       - Facebook engagement quality
       - Instagram virality potential
       - WhatsApp conversational effectiveness

    3. Content Evaluation Metrics
       - Readability score
       - Emotional engagement
       - CTA effectiveness
       - Audience targeting quality
       - Marketing strength
       - Conversion potential

    4. Improvement Recommendations
       - Better hashtags
       - Better CTA suggestions
       - Shortening/expanding content
       - Improving emotional triggers
       - Improving engagement hooks

    5. Final Campaign Score
       Provide scores out of 10 for:
       - Engagement
       - Clarity
       - Conversion potential
       - Virality
       - Brand alignment

    Output Requirements:
    - Use markdown formatting
    - Use professional formatting
    - Include bullet points
    - Highlight strengths and weaknesses
    - Keep analysis structured and readable
    """,
)